---
{{- if .Values.twemproxy.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "twemproxy" . }}
  labels:
    app: {{ template "twemproxy" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.twemproxy.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "twemproxy" . }}
    spec:
      nodeSelector:
        tier: redis
      containers:
        - name: {{ template "twemproxy" . }}
          image: {{ .Values.twemImage }}
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "1700Mi"
              cpu: "500m"
            limits:
              memory: "1700Mi"
              cpu: "500m"
          env:
            - name: "SERVERS"
              value: "{{- $root := . -}}{{ template "fullname" $root }}-0:6379:1{{- range $i, $e := until ( sub ( .Values.twemproxy.replicaCount | int) 1 | int ) }},{{ template "fullname" $root }}-{{ add $e 1 }}:6379:1{{- end -}}"
---
 {{ end }}